// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXQt8kHQMyY6WUaouG5UOiTe4NHH5bea0',
    appId: '1:327226921382:web:5d06b579b8f694f8e7ff67',
    messagingSenderId: '327226921382',
    projectId: 'app-608aa',
    authDomain: 'app-608aa.firebaseapp.com',
    storageBucket: 'app-608aa.firebasestorage.app',
    measurementId: 'G-3EF68K4V6E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcU0P3uWGyKvj1uf4u1_x3PE_VSTVF7ww',
    appId: '1:327226921382:android:d4fafd665b63a677e7ff67',
    messagingSenderId: '327226921382',
    projectId: 'app-608aa',
    storageBucket: 'app-608aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFeGJffGOIt2KEidv2FhwLrx-Hg071Ycg',
    appId: '1:327226921382:ios:7d2720a5e692baeee7ff67',
    messagingSenderId: '327226921382',
    projectId: 'app-608aa',
    storageBucket: 'app-608aa.firebasestorage.app',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFeGJffGOIt2KEidv2FhwLrx-Hg071Ycg',
    appId: '1:327226921382:ios:7d2720a5e692baeee7ff67',
    messagingSenderId: '327226921382',
    projectId: 'app-608aa',
    storageBucket: 'app-608aa.firebasestorage.app',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXQt8kHQMyY6WUaouG5UOiTe4NHH5bea0',
    appId: '1:327226921382:web:96dd8ef4cd1581ece7ff67',
    messagingSenderId: '327226921382',
    projectId: 'app-608aa',
    authDomain: 'app-608aa.firebaseapp.com',
    storageBucket: 'app-608aa.firebasestorage.app',
    measurementId: 'G-H797D8D7N6',
  );
}
