// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYQa_pmlg3xXuPUTDzawzxd4htqu6K23c',
    appId: '1:71696684032:web:7804cbb1bc238dca7af4e5',
    messagingSenderId: '71696684032',
    projectId: 'music-app-pro-v2',
    authDomain: 'music-app-pro-v2.firebaseapp.com',
    storageBucket: 'music-app-pro-v2.firebasestorage.app',
    measurementId: 'G-X3R8PNPZ36',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBakqZPE9ROZVEiOkLVydsJlz9Q3VF4tsU',
    appId: '1:71696684032:android:616ea0e30cd065557af4e5',
    messagingSenderId: '71696684032',
    projectId: 'music-app-pro-v2',
    storageBucket: 'music-app-pro-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBP9sM7_bbxVWjYGj7L4oUBxmd1y3-Y9o',
    appId: '1:71696684032:ios:9903c3810347b6d47af4e5',
    messagingSenderId: '71696684032',
    projectId: 'music-app-pro-v2',
    storageBucket: 'music-app-pro-v2.firebasestorage.app',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBP9sM7_bbxVWjYGj7L4oUBxmd1y3-Y9o',
    appId: '1:71696684032:ios:9903c3810347b6d47af4e5',
    messagingSenderId: '71696684032',
    projectId: 'music-app-pro-v2',
    storageBucket: 'music-app-pro-v2.firebasestorage.app',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYQa_pmlg3xXuPUTDzawzxd4htqu6K23c',
    appId: '1:71696684032:web:3c8e699c474ec8917af4e5',
    messagingSenderId: '71696684032',
    projectId: 'music-app-pro-v2',
    authDomain: 'music-app-pro-v2.firebaseapp.com',
    storageBucket: 'music-app-pro-v2.firebasestorage.app',
    measurementId: 'G-FE2SRN8GB7',
  );
}
